# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  A_cart_joint:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  A_joint_1:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  A_joint_2:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  A_joint_3:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  A_joint_4:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: false
    max_acceleration: 0
  A_joint_5:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: false
    max_acceleration: 0
  A_joint_6:
    has_velocity_limits: true
    max_velocity: 7.854
    has_acceleration_limits: false
    max_acceleration: 0
  B_cart_joint:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  B_joint_1:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  B_joint_2:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  B_joint_3:
    has_velocity_limits: true
    max_velocity: 2.618
    has_acceleration_limits: false
    max_acceleration: 0
  B_joint_4:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: false
    max_acceleration: 0
  B_joint_5:
    has_velocity_limits: true
    max_velocity: 6.2832
    has_acceleration_limits: false
    max_acceleration: 0
  B_joint_6:
    has_velocity_limits: true
    max_velocity: 7.854
    has_acceleration_limits: false
    max_acceleration: 0